// AUTO-GENERATED by scripts/build-cms-media.mjs — do not edit by hand.
// Regenerated on every build from CMS-uploaded film imagery.
import type { ProjectMedia } from "./project-media";

export const CMS_MEDIA: Record<string, ProjectMedia> = {};
