// AUTO-GENERATED by scripts/build-cms-media.mjs — do not edit by hand.
// Regenerated on every build from CMS-uploaded imagery.
import type { ImageMeta, ProjectMedia } from "./project-media";

export const CMS_MEDIA: Record<string, ProjectMedia> = {};

export const FOOTER_MEDIA: ImageMeta | null = null;
