// AUTO-GENERATED by scripts/optimize-project-images.mjs — do not edit by hand.
// Run `node scripts/optimize-project-images.mjs` to regenerate.

export interface ImageMeta {
  src: string;
  blurDataURL: string;
  width: number;
  height: number;
}

export interface ProjectMedia {
  cover: ImageMeta;
  gallery: ImageMeta[];
}

export const PROJECT_MEDIA: Record<string, ProjectMedia> = {
  "cuirdange": {
    "cover": {
      "src": "/projects/cuirdange/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoQAAcAAsBMJYwCdAEVzm/Mji6AAP7ysLDDeQ63FtkbBewGjIL4Nk70tB8V8AAA",
      "width": 2000,
      "height": 838
    },
    "gallery": [
      {
        "src": "/projects/cuirdange/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoQAAcAAsBMJZQC7AEN0LkAAP74oBPdTLb8LuKvj0FcV0PkhmzIAAAA",
        "width": 1201,
        "height": 531
      },
      {
        "src": "/projects/cuirdange/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAcAAsBMJaQAAqH2VpwAAP75F7fNLFkP9RE+/uXSFiauqLwVupnx71d/KCgA",
        "width": 2000,
        "height": 838
      },
      {
        "src": "/projects/cuirdange/gallery-3.webp",
        "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAcAAsBMJYwAAiDPwHPIAAD+807DAEToi7CCh9idMTiz9fyruITuGjHn9/HY71BuD4xj0yYcD/SXQyYAAA==",
        "width": 2000,
        "height": 838
      },
      {
        "src": "/projects/cuirdange/gallery-4.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoQAAcAAsBMJZwC7AEOmFrM4QAA/vKiA278mvSJ6XZJcmlg+pxk0AAA",
        "width": 2000,
        "height": 838
      },
      {
        "src": "/projects/cuirdange/gallery-5.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAABwAQCdASoQAAoAAsBMJZwCw7F1AAD+9vMFNeIKNNvVkvWAAAA=",
        "width": 1911,
        "height": 1140
      }
    ]
  },
  "jail-time-records": {
    "cover": {
      "src": "/projects/jail-time-records/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAkAAsBMJZwAAwF1elFBR84AAP7ts176j4VeX9rbmti8NlyhbLQvpnLtD5sfq1Oa2eVuDJpzgfhFnw8yf823IAA=",
      "width": 2000,
      "height": 1129
    },
    "gallery": [
      {
        "src": "/projects/jail-time-records/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoQAAkAAsBMJZwC7AB/eoAA/p6hJGkJrZ0t0Kkna1MNR9Rqta+Y6AAA",
        "width": 2000,
        "height": 1127
      },
      {
        "src": "/projects/jail-time-records/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAoAAsBMJaQAAp3QhWiFgAAA/u0hDZBmxoSr76ySC70d+i0DV9+10n4pqxKt4yfADe+OovuCdou2vDZ60jvgVYh8VXP37XL3PQMPcfSlIunmCU9wAAAA",
        "width": 2000,
        "height": 1210
      },
      {
        "src": "/projects/jail-time-records/gallery-3.webp",
        "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAAsBMJZQCdAEW098SVq4AAP74bW/kSMP/V45xM2Z93pgHsIfx9rPMuHWvuatUGWSJO5kqJkPny+Hq/i+Fvwbh6nSAAAA=",
        "width": 1800,
        "height": 1013
      },
      {
        "src": "/projects/jail-time-records/gallery-4.webp",
        "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAAsBMJYgCdAEORWduRAD+3Oyuj6ryBPHPej9WCJGztpjwaP1liqC2G8d2FgiAvjFXVWBRY5bLhKIfqmgjUE8EEiyDNDAAAA==",
        "width": 1800,
        "height": 1013
      }
    ]
  },
  "la-tempesta": {
    "cover": {
      "src": "/projects/la-tempesta/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoQAAgAAsBMJZwAAudQQDzOAP76ivZR7isWj3lCl3MZ/0Kuiaa1Fs8cUIBsq0tIAAA=",
      "width": 2000,
      "height": 1052
    },
    "gallery": [
      {
        "src": "/projects/la-tempesta/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoQAAoAAsBMJaQAAujdBJTgAAD++J+SmqZPkaHKfspSTDn84UAAAA==",
        "width": 2000,
        "height": 1201
      },
      {
        "src": "/projects/la-tempesta/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAgAAsBMJZQCdH8AGZ9egv+AAP73wIzkfKYqRxnPs7QMVKcMDx17Nk+zhpAOwmRVgAAA",
        "width": 2000,
        "height": 997
      },
      {
        "src": "/projects/la-tempesta/gallery-3.webp",
        "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAkAAsBMJZwCw7Ef/yLyNjAAAP7d3hrUeHRDKDU168rvKQ1QNNAhndLr75EpvNnD+AgA",
        "width": 2000,
        "height": 1125
      }
    ]
  },
  "noia": {
    "cover": {
      "src": "/projects/noia/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAYAAsBMJaQAAucPY6dAAP74lbnvyUCApS17L0/t2MP018AJuE/QdjXoge4ypE6AAA==",
      "width": 2000,
      "height": 773
    },
    "gallery": [
      {
        "src": "/projects/noia/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAcAAsBMJaQAD4nNnbJkgAD+7SlKnby2Wd0/WwTnMTWv0R92Ht5ZhDBOIMRq3Xyd3yQKQaIKacR5jZd2cxVCZn1FtvqgAAA=",
        "width": 2000,
        "height": 833
      },
      {
        "src": "/projects/noia/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAcAAsBMJaQAAq36mxVgAP74nrhkSvcoOv6sRs9NzGeiKCt8vV/2FCrNSk1F4VxnTHDn8QH71nz0AAA=",
        "width": 2000,
        "height": 833
      },
      {
        "src": "/projects/noia/gallery-3.webp",
        "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAYAAsBMJaQAAkra6UAAAP77bns81E4DNLq/tlUgPpBFwNQJ7qnhLKO2Cn9aWWQ4jAU7qDPtrpF1LAAAAA==",
        "width": 2000,
        "height": 788
      }
    ]
  },
  "maree": {
    "cover": {
      "src": "/projects/maree/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAcAAsBMJZQCw7Dyq55VgAD+9HiKdYwY69HV55JYUdfAWWnpGAAA",
      "width": 2000,
      "height": 831
    },
    "gallery": [
      {
        "src": "/projects/maree/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAcAAsBMJbACdAEfaw1GYAD+9AiAD6YDfvSN/B+LzwrV0263a4EHxItEfjo78EmqvElhCUUzn/5a2EZeWgsOTp+W4nSM/ksf/edq9f2hDfO9CzZTMAAA",
        "width": 2000,
        "height": 828
      },
      {
        "src": "/projects/maree/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoQAAUAAsBMJQBOjXAAWbWXUQAA/tz+35J7aHDVv8vOS+JyIpM2AAAA",
        "width": 2000,
        "height": 609
      },
      {
        "src": "/projects/maree/gallery-3.webp",
        "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAYAAsBMJYwCdAYqXbM6z1gAAP767/cCgk73o2/7jZbvdSkJbMpYljQAbC0kRGASf5NJvoAAAA==",
        "width": 2000,
        "height": 766
      },
      {
        "src": "/projects/maree/gallery-4.webp",
        "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAcAAsBMJbACdAEQXG8kdfAA/sT7b03DBCF2cBwpFyUJJuZcVHQ8+L3CiowBbMM+iaHfEft+z5vsX45dHSsapYGDyKN98TgmgAAA",
        "width": 2000,
        "height": 832
      }
    ]
  },
  "kiss-of-an-angel": {
    "cover": {
      "src": "/projects/kiss-of-an-angel/hero.webp",
      "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAkAAsBMJQBOgCFflu0AAP7y+BaK+t/LixaL5TSzu4s8TJHox/7wAAA=",
      "width": 2000,
      "height": 1115
    },
    "gallery": [
      {
        "src": "/projects/kiss-of-an-angel/gallery-1.webp",
        "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAkAAsBMJYwCdACpSHW4APnrcd/qNlO950X3dBaYRgcz6F/z6bmINAA=",
        "width": 2000,
        "height": 1138
      },
      {
        "src": "/projects/kiss-of-an-angel/gallery-2.webp",
        "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAkAAsBMJQBOgBcT8qaAAPpN+7kMkdVLgBFHVuuvGbVawPgrdnKCSrRwknnNBHZd/hGGsVLgAA==",
        "width": 2000,
        "height": 1124
      }
    ]
  }
};
